import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`CREATE TABLE todos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255) NOT NULL,
    author_id int,
    CONSTRAINT fk_author
      FOREIGN KEY(author_id) 
	      REFERENCES users(id)
  )`);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE todos`);
}
